### ISSUE TITLE
extract_roi fails if there is only 1 image in a Brain_Data object

### ISSUE THREAD

**Issue by ejolly** [cosanlab/nltools#104]
Need to check self.shape to make sure there is more than 1 dimension in the numpy array otherwise this [line](https://github.com/ljchang/nltools/blob/master/nltools/data.py#L938) fails.

**Comment by ljchang** [comment]
Can you send more info? is it one image in the target or the mask?

**Comment by ejolly** [comment]
Sorry I meant if there's a single "row" in the 2d `Brain_Data` not the mask, e.g.

if `brain` contains a single map it typically has 1d (nvoxels), rather than (1, nvoxels). In this case `brain.extract_roi(mask)` fails with a `too many indices for array` error, because both of the following lines in `extract_roi` are indexing `brain.data` assuming it's 2d: 

https://github.com/cosanlab/nltools/blob/679dbb5bb40e3ce5a0b46f2dcedd20b69caa9a27/nltools/data/brain_data.py#L1241

https://github.com/cosanlab/nltools/blob/679dbb5bb40e3ce5a0b46f2dcedd20b69caa9a27/nltools/data/brain_data.py#L1248

**Comment by ejolly** [comment]
One potential solution to this is to provide a Value error or something because you can't actually call `extract_roi` and get a mean over time without more than 1 row. 

The other option though, which is probably better is to just return the spatial mean in the ROI (i.e. equivalent to calling `apply_mask` and then taking the mean of the return object), and kick a warning that tells the user there is only 1 observations so the return value is a spatial mean.

**Comment by ljchang** [comment]
> Sorry I meant if there's a single "row" in the 2d `Brain_Data` not the mask, e.g.
> 
> if `brain` contains a single map it typically has 1d (nvoxels), rather than (1, nvoxels). In this case `brain.extract_roi(mask)` fails with a `too many indices for array` error, because both of the following lines in `extract_roi` are indexing `brain.data` assuming it's 2d:
> 
> https://github.com/cosanlab/nltools/blob/679dbb5bb40e3ce5a0b46f2dcedd20b69caa9a27/nltools/data/brain_data.py#L1241
> 
> https://github.com/cosanlab/nltools/blob/679dbb5bb40e3ce5a0b46f2dcedd20b69caa9a27/nltools/data/brain_data.py#L1248

Figured this one out. Modified the mean and added a median function to make this cleaner. Also, added a bunch of new tests to make sure all of the edge cases are tested.

Fixed in  PR #331
