### ISSUE TITLE
Need to refactor searchlight and add tests

### ISSUE THREAD

**Issue by ljchang** [cosanlab/nltools#168]
Maybe we can use [nilearn's version](https://github.com/nilearn/nilearn/blob/c842617f46384d764707ae6a4335edad4f4684dc/nilearn/decoding/searchlight.py)?  

the pbs_job.py module isn't really general enough to be used outside of the lab and might need to be migrated to a different package.  Maybe our preprocessing one?  This will also dramatically improve our test coverage.

**Comment by ejolly** [comment]
This was added with the addition of `Brain_Data.predict_multi()`
