### ISSUE TITLE
add ability to easily perform contrasts with Brain_Data

### ISSUE THREAD

**Issue by ljchang** [cosanlab/nltools#235]
Currently, you have to multiply a contrast vector by Brain_Data.data.  I could see two possible solutions to this.

1) add a dot() or contrast() method, where you pass in a vector of contrast weights and matrix multiplication is applied.  Advantage of this is that we could have a default flag to make sure it is balanced.

2) add ability to multiply by vector, the advantage of this is that it is very intuitive to use.  Disadvantage is that we would have to add checks about whether performing left or right multiplication and it would be up to user to make sure contrast is balanced.

**Comment by ejolly** [comment]
I propose we add both because 2) could also be very useful in non-contrast situations in which we want to generally apply some vector transform to `Brain_Data`, (e.g. apply previously learned dimensionality reduction solution to a new instance).

**Comment by ljchang** [comment]
we added the vector multiplication option.
