### ISSUE TITLE
Fix duplicated plots

### ISSUE THREAD

**Issue by ejolly** [cosanlab/nltools#241]
Plot methods, e.g. `Brain_Data.plot()` and `Adjacency.plot()` are duplicating plots in jupyter notebooks. Not quite sure why, but not related to `limit` arg.

**Comment by ljchang** [comment]
This would be great to fix as well as being able to add to subplots.  it's returning a figure handle.  If you assign it to a variable the double plot goes away, super annoying.

f = dat.plot()
