### ISSUE TITLE
Get a DOI

### ISSUE THREAD

**Issue by ejolly** [cosanlab/nltools#242]
Now that there is much more diverse functionality in the package, we should make this package citable with a DOI. It's super easy using [github+zenodo](https://guides.github.com/activities/citable-code/). We can even consider combining this with [JOSS](https://joss.theoj.org/) , which requires a brief 1 page manuscript

**Comment by Das-Boot** [comment]
Hi, I want to cite nltools in my paper. Could you please offer me a citation (BibTex version)?
