### ISSUE TITLE
Holm_bonf returns incorrect p value

### ISSUE THREAD

**Issue by elvandy** [cosanlab/nltools#252]
FDR needs to return an adjusted p value. Holm_bonf does not return the right corrected p value

**Comment by ejolly** [comment]
Can confirm that hom_bonf does need to be fixed

**Comment by ljchang** [comment]
who wrote that function?  FDR works as it should be.

**Comment by ejolly** [comment]
I wrote `holm_bonf`, I think the @elvandy was referring to the fact, that it's common in other software to return a list of adjusted p-values by applying the benjamini-hochberg (FDR) procedure. The way that Tal wrote it, doesn't do anything wrong of course, but it would be nice if it could return a list of adjusted values. Or we could write a separate function to do that. This is what `holm_bonf` does for you and is very useful (save for a minor bug I need to fix).

**Comment by ljchang** [comment]
As I explained to @elvandy, FDR does return the adjusted p-value.  The adjusted p-value can only be calculated from the set of p-values passed to it.  It's adaptive so you don't know what the threshold would have been if you had passed a different set of p-values, that's why it returns -1.

**Comment by ljchang** [comment]
Sorry, I meant it returns the thresholded p-value for the specified q-value.

**Comment by ejolly** [comment]
Yup I get that, but it's pretty common to actually return a list of adjusted p-values as a result of the FDR procedure i.e. `adjusted_p = rank/num_tests * q`, which is often very (argubly more) useful. For example see statsmodels implementation here which returns that: http://www.statsmodels.org/devel/_modules/statsmodels/stats/multitest.html#fdrcorrection

**Comment by ljchang** [comment]
I'm not sure that is more useful, but it's fine to add a flag to return all adjusted p-values.  Just don't change the default behavior of this function.

**Comment by ejolly** [comment]
Didn't add a flag, but fixed `holm_bonf`  to act like `fdr`, returning a p-value threshold in PR #256

**Comment by ejolly** [comment]
Fixed in #256
