### ISSUE TITLE
Handle divide by zero errors at brain edge during regression

### ISSUE THREAD

**Issue by ejolly** [cosanlab/nltools#258]
Sometimes edge of the brain/cerebellum voxels have no standard error so `t = b / stderr` produces warnings and masking returns warnings as well. And easy way around this is something like what nipype does when computing tSNR:

```
# Rather than simply
t = b / stderr 

# Initialize an empty brain first
t = np.zeros_like(b)
# Then only compute t-stats at voxels where the standard error is at least .001
t[stderr > 1.e-3] = b[stderr > 1.-3] / stderr[stderr > 1.e-3]  
```

**Comment by ljchang** [comment]
fixed in PR #286

**Comment by ejolly** [comment]
Are you sure it's fixed in that PR? I don't think I did this

**Comment by ljchang** [comment]
Oh, sorry, I thought this is one of the things you fixed.
