### ISSUE TITLE
Add axis argument to Brain_Data.standardize

### ISSUE THREAD

**Issue by ejolly** [cosanlab/nltools#259]
Sometimes it's desirable to compute feature-wise normalization to remove inter-voxel mean activity differences before doing pattern classification.

Also we might not want to reinvent the wheel with this method as can just use `scipy zscore` or `sklearn scale` as both libraries are already dependencies.

**Comment by ejolly** [comment]
Could also potentially merge this with https://github.com/cosanlab/nltools/issues/42 and add flag for various scaling methods.

**Comment by ljchang** [comment]
this is fine with me if you want to submit a PR

**Comment by ejolly** [comment]
Added to PR #256
