### ISSUE TITLE
check_brain_data should take a mask argument

### ISSUE THREAD

**Issue by ejolly** [cosanlab/nltools#264]
Just noticed that this should take an optional mask argument in case the user is already working with a custom mask. Otherwise, it uses the default `Brain_Data` mask with no ability to change it. 

https://github.com/cosanlab/nltools/blob/master/nltools/utils.py#L240

**Comment by ljchang** [comment]
@ejolly check the commit in bug_fix to make sure this will handle the use case you were thinking of.
