### ISSUE TITLE
Documentation is out of date

### ISSUE THREAD

**Issue by ejolly** [cosanlab/nltools#271]
Not sure what's happening but some newer functions like `nltools.mask.roi_to_brain` are undocumented.

**Comment by ejolly** [comment]
Team effort to document whats wrong with docs here: https://docs.google.com/document/d/1pJjNk2RuNo_WHFwRRjTgk7cqTd4lc4aQfcCk68xXjGU/edit

**Comment by ljchang** [comment]
Issue rebuilding documentation was due to some conflicts with pip, conda, and readthedocs.  Seemed to be similar to https://github.com/rtfd/readthedocs.org/issues/5545#issuecomment-483654224.

Switching:

```
python:
    pip_install: true
```
to

```
python:
    setup_py_install: true
```
Seemed to allow the conda environment to build successfully.
