### ISSUE TITLE
Consider making a attribute setter for Brain_Data

### ISSUE THREAD

**Issue by ejolly** [cosanlab/nltools#275]
Basically whenever we return a new Brain_Data instance from a method, we should pass in all the same attributes that _arent_ changed by that function, e.g. maybe the X, Y, and/or mask.

Here's the same idea implemented in Design_Matrix: https://github.com/cosanlab/nltools/blob/master/nltools/data/design_matrix.py#L85

**Comment by ljchang** [comment]
see discussion in #283
