### ISSUE TITLE
Speed up Brain_Data.apply_mask

### ISSUE THREAD

**Issue by ejolly** [cosanlab/nltools#309]
Aside from type-checking/loading a mask file, it seems like using simple boolean indexing in numpy is a much faster alternative to masking data rather than relying on `NiftiMasker`. 

For example `brain.apply_mask(roi)` can be sped up several times by simply doing:  
```
out = roi.copy()
out.data = brain.data[:, roi.data.astype(bool)]
```

**Comment by ljchang** [comment]
in principle this should work if the images are in the same shape.  However, often masks are not the full 328k and only include a subset of voxels, which means you will need to use the nifti_masker.  I'm okay with using logical indexing it as long as you put a check to make sure images are from same shape.
