### ISSUE TITLE
All dunder arithmetic methods silently fail for np.float32

### ISSUE THREAD

**Issue by ejolly** [cosanlab/nltools#320]
@ljchang This is a pretty scary and but hard to find bug that drove me insane. In all dunder methods (e.g. `__mult__`) type-checking silently fails if the input datatype is `np.float32`, because `np.float32` is not an instance of a `float`, e.g.

`isinstance(np.array([1],dtype=np.float32)[0], (int,float)) # False`
`isinstance(np.array([1],dtype=np.float64)[0], (int,float)) # True`

Turns out they also fail for int16, int32, etc. These aren't all that typical data types in pure Python or numpy where we typically use `int`, `float`, `np.integer` and `np.float` but they do occur in neuroimaging data files on occasion as the output of other software (e.g. FSL). 

The reason this silent fail occurs is because all your type checks for both `Adjacency` and `Brain_Data` dunder methods don't have an `else` clause, only `if isinstance(...)` and `elif ..`, was this intentional? It's generally bad practice to not end a conditional with an `else` clause. 

 I encountered it when trying to use `roi_to_brain` with a list that contained integers, cast to a numpy array, which numpy decided to use `float32` for. No errors, but I kept getting back a mask of ROIs instead of values _at those_ ROIs as expected. 

This is a major concern because any method, or custom code that relies on these arithmetic operations has the potential to produce an output without errors but containing results that the user doesn't realize is not what they wanted.

**Comment by ljchang** [comment]
Yikes, definitely not intentional. Let's fix this one ASAP.

**Comment by ljchang** [comment]
ok, easy fix, but still scary.
np.integer and np.floating will add all numpy variants to test.
