### ISSUE TITLE
FDR considers p == 0.

### ISSUE THREAD

**Issue by mpcoll** [cosanlab/nltools#324]
Hi, 

Thanks for the great package. 

The API for the *nltools.stats.fdr* says *p – (np.array) vector of p-values (only considers non-zero p-values)*. However, from the code, I'm pretty sure the p values == 0. are also considered in the FDR correction. Am I missing something?

Thanks!

**Comment by ejolly** [comment]
Hey @mpcoll this looks like an issue with the docstring of the function, but the intended output of the function should be correct. It's based off of the same function in [neurosynth-tools](https://github.com/neurosynth/neurosynth/blob/master/neurosynth/analysis/stats.py).

Sorry for the confusion.
