### ISSUE TITLE
onsets_to_dm() function starts boxcar one TR too early when onset file contains 'Duration' values

### ISSUE THREAD

**Issue by BryanGonzalez262** [cosanlab/nltools#325]
in file_reader.py, onsets_to_dm function
If an onset file contains 3 columns (line 78), the "1" indicating a boxcar stimulus onset is set one TR before its actual onset by line 80.

**Comment by ljchang** [comment]
I think this is resolved now. we decided to be more inclusive by rounding to floor., but there is an option to not do this.
