### ISSUE TITLE
ImportError: cannot import name 'misc' from 'nltools' (E:\Anaconda\lib\site-packages\nltools\__init__.py)

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [cosanlab/nltools#346]
I am trying to run `python abook-segment.py -h`

I get

```
E:\Anaconda\lib\site-packages\sklearn\utils\deprecation.py:144: FutureWarning: The sklearn.linear_model.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.linear_model. Anything that cannot be imported from sklearn.linear_model is now part of the private API.
  warnings.warn(message, FutureWarning)
Traceback (most recent call last):
  File "abook-segment.py", line 32, in <module>
    from nltools            import misc
ImportError: cannot import name 'misc' from 'nltools' (E:\Anaconda\lib\site-packages\nltools\__init__.py)
```

I installed `nltools` via `pip` and also from source, but each time there is no `misc` in it.

**Comment by ljchang** [comment]
Hi, sorry you are having issues. We might need more information about what you are trying to do, plus the version of nltools and python you are using.  We don't currently have a `misc` module in nltools.

**Comment by ejolly** [comment]
hey @ErfolgreichCharismatisch from the traceback you posted I'm assuming you were trying to use this [zamia-speech]() repository, which has a dependency of **[py-nltools](https://github.com/gooofy/py-nltools)** not **nltools** (this library). 

Installing the correct dependency should solve your issue.
