### ISSUE TITLE
Conflict between tpot and joblib versions

### ISSUE THREAD

**Issue by nosratullah** [cosanlab/nltools#350]
Hi,
I installed nltools, It gives me the hint that tpot version requires joblib==0.13.2 and when I install joblib 0.13.2 it says that nltools require joblib==0.11 which is frustrating. 
No error yet and everything seems to work fine, just a hint for your next upgrade.
Thanks for the cool package btw.

**Comment by ljchang** [comment]
Thanks @nosratullah, looks like newer versions of joblib are working now, we've updated the requirements.
