### ISSUE TITLE
Brain_Data class in Python 3.8

### ISSUE THREAD

**Issue by esfinn** [cosanlab/nltools#365]
Since upgrading to Python 3.8 I get a cryptic error `AttributeError: ‘_io.BytesIO’ object has no attribute ‘mode’` anytime I am working with Brain_Data. I am able to load data in as a Brain_Data object, but any kind of method/operation on it fails with that same error (e.g., `.filter`, `.smooth`, and `.to_nifti()`). Pretty sure Python version is the issue since it still works fine in environments with 3.7.

**Comment by ljchang** [comment]
hopefully, this issue is now resolved.
