### ISSUE TITLE
ttest 'permutation' question

### ISSUE THREAD

**Issue by dabinyeum** [cosanlab/nltools#366]
Hi all,

I have a question regarding the permutation test in the ttest function.

I was able to run and plot different thresholds of the ttests such as:
`Comm_v_Stat_avg_stats_unc = Comm_v_Stat_avg.ttest(threshold_dict={'unc':.001})`
`Comm_v_Stat_avg_stats_fdr = Comm_v_Stat_avg.ttest(threshold_dict={'fdr':.05})`

I was trying to run the permutation test under the same function using this code:
`Comm_v_Stat_avg_stats_perm = Comm_v_Stat_avg.ttest(threshold_dict = {'permutation':'tfce', 'n_permutations':1000})`
and got this error message.
<img width="997" alt="Screen Shot 2021-01-11 at 4 46 22 PM" src="https://user-images.githubusercontent.com/55110485/104156535-99c43900-542c-11eb-9bff-dca259995828.png">

Please provide feedback as to how I can make this code run or if I did anything incorrectly.
Thanks for your help!

**Comment by ljchang** [comment]
hi @dabinyeum, We are planning on updating that feature soon. Currently that method requires that you have the MNE package installed, which is an optional requirement. This method is fairly limited as most computers can't run this on whole brain. We are (slowly) working on adding some of the accelerated bootstrap/permutation methods

**Comment by dabinyeum** [comment]
> hi @dabinyeum, We are planning on updating that feature soon. Currently that method requires that you have the MNE package installed, which is an optional requirement. This method is fairly limited as most computers can't run this on whole brain. We are (slowly) working on adding some of the accelerated bootstrap/permutation methods

Thank you so much for the reply!

**Comment by ljchang** [comment]
going to remove this now to prevent code rot.

**Comment by ljchang** [comment]
we have removed the MNE permutation support in #389
