### ISSUE TITLE
Clarify distance_to_similarity

### ISSUE THREAD

**Issue by jcheong0428** [cosanlab/nltools#367]
[`distance_to_similarity` method for Adjacency class](https://github.com/cosanlab/nltools/blob/91822a45778415ee2cdded7134e60bcde2bb7814/nltools/data/adjacency.py#L1000) is specific for converting a Euclidean distance to similarity. This would not be appropriate for converting a correlation distance to similarity (1-r). 

Might be worth clarifying this by adding an argument that specifies what distance metric is being converted (euclidean or correlation) to use either the exponential or the 1-r conversion.

**Comment by ljchang** [comment]
fixed

**Comment by ljchang** [comment]
Fixed in #389
