### ISSUE TITLE
switch between Brain_Data object and a pandas dataframe

### ISSUE THREAD

**Issue by chuanjig** [cosanlab/nltools#375]
Hi,
I'm wondering how can I extract a pandas dataframe from a Brain_Data class object?
For example, I have a dat1 variable (Brain_Data class), 800 x 238955;
and I also have a dat2 variable (pandas dataframe), 800 x 7.
I'd like to merge them together into a pandas dataframe. Ideally, it can be done df = pd.concat([dat1, dat2]).
However, Brain_Data cannot be merged directly. How can I extract a dataframe from Brain_Data?
Thanks in advance,
Chuanji

**Comment by ejolly** [comment]
Hey @chuanjig you can always access the underlying 1d or 2d *numpy array* using the `.data` attribute of `Brain_Data`. From there you can convert the numpy array to a pandas dataframe and proceed as you like.

**Comment by chuanjig** [comment]
Thanks very much! I'm pretty new to python, that helps a lot.
