### ISSUE TITLE
add  a silent option to Brain_Data.predict

### ISSUE THREAD

**Issue by jvschw** [cosanlab/nltools#392]
Dear all,
it would be nice to have an option to suppress predict's console output.

Cheers
Jens

def predict(self, algorithm=None, cv_dict=None, plot=True, silent=False, **kwargs):
.
.
.
if not silent:
    print("overall accuracy: %.2f" % output["mcr_all"])

similar for
           print("overall Root Mean Squared Error: %.2f" % output["rmse_all"])
           print("overall Correlation: %.2f" % output["r_all"])

and
                print("overall CV Root Mean Squared Error: %.2f" % output["rmse_xval"])
                print("overall CV Correlation: %.2f" % output["r_xval"])

**Comment by ljchang** [comment]
Great suggestion @jvschw . We'll add that in our next update.
