### ISSUE TITLE
 No module named 'sklearn.linear_model.base' on Brain_Data import

### ISSUE THREAD

**Issue by kylestanley1313** [cosanlab/nltools#400]
When importing the `Brain_Data` class from `nltools.data` I get a `ModuleNotFoundError` for `sklearn.linear_model.base`.

### Steps to Reproduce

Python version: 3.9.7

Package versions:
```
scikit-learn==1.0.1
nltools==0.4.5
```

### Current Behavior

<img width="1005" alt="Screen Shot 2021-10-29 at 8 16 31 AM" src="https://user-images.githubusercontent.com/44176344/139432759-8bc86519-8db3-4352-98e5-f3b9f872dda5.png">

### Expected Behavior

Successful import

### Other Notes

The latest version of `scikit-learn` has a `klearn.linear_model._base` module, but not a `klearn.linear_model.base` module.

**Comment by Kishanji0319** [comment]
I also face this error but when i tried this method whenever faced this problem!
Anyone can help me to get out from this error.
