### ISSUE TITLE
Design_Matrix.clean() method does not work with parameters fill_na = None and exclude_polys = True

### ISSUE THREAD

**Issue by briannaaubrey** [cosanlab/nltools#413]
The .clean() method from the Design_Matrix class has an error that prevents both fill_na = None and exclude_polys = True from being included as parameters. If exclude_polys is True and fill_na is None, line 790 ( "out = out[data_cols]") references a dataframe that was never created, producing the error "local variable 'out' referenced before assignment". I've attached a screenshot of the error and the lines of code that create the problem.
<img width="742" alt="image" src="https://user-images.githubusercontent.com/126296310/221317653-1700ba1c-e946-4baf-8d5b-bee86b2e994f.png">
<img width="574" alt="image" src="https://user-images.githubusercontent.com/126296310/221317471-5b8af8a0-5313-41b9-8089-085ea4cfc2c1.png">

**Comment by ljchang** [comment]
thanks @briannaaubrey for sharing this issue. We will look into this and get back to you.

**Comment by ljchang** [comment]
@briannaaubrey , I think we have this fixed in #414, but might take a bit before it gets merged. So cool to see that you are still using nltools and also opening issues with suggested fixes!  Hope everything is going well!

**Comment by ejolly** [comment]
@briannaaubrey Installing directly from the main/master branch on github should now have this fix!
