### ISSUE TITLE
Drop deepdish for h5py

### ISSUE THREAD

**Issue by ejolly** [cosanlab/nltools#415]
Deepdish doesn't seem to be under development any more: https://github.com/uchicago-cs/deepdish/pull/49#issuecomment-1470027826

It also fails for the latest version of numpy 1.24, due to enforced API deprecations. I've currently pinned us to `numpy<1.24`, but we should drop it as a dependency and switch over to h5py ASAP, which has long term support from the HDF5 team. But this will require a bit of rewriting for how we're saving and loading `Brain_Data` and `Adjacency` objects

**Comment by ljchang** [comment]
@ejolly. Apologies for the delay. Seems like it is reading and writing data ok. I propose merging this and unpinning the old versions of numpy. thanks!

**Comment by ejolly** [comment]
Done in #416
