### ISSUE TITLE
Replace custom stats.procrustes with scipy import

### ISSUE THREAD

**Issue by ejolly** [cosanlab/nltools#417]
Our `stats.procrustes` is literally just the source code for `scipy.spatial.procrustes` so we should replace it with an import: https://github.com/cosanlab/nltools/blob/8f034dbbbb788fc09cda9be3bd26cdf5eb5e421f/nltools/stats.py#L1435

**Comment by srken32** [comment]
@ejolly 
I tried replacing with an import but this caused new errors- it seems like the custom procrustes returns two more variables (R and s) than scipy.spatial's method returns, and nltools' version allows the matrices to have a different number of columns? I think the scipy.spatial procrustes source code returns 3 values compared to 5 and the matrices must be the same shape. I am basing these findings on this link: https://github.com/scipy/scipy/blob/main/scipy/spatial/_procrustes.py (see lines 105-108 as compared to 1481-1496 and line 131 vs 1519). Let me know what you think!

**Comment by ejolly** [comment]
@srken32 Ah I see. I can' think of a clever way to get out those inputs without calling a function multiple times or just duplicating the code like we currently have. Let's just leave it for now. Thanks for looking into it!
