### ISSUE TITLE
cut beta images

### ISSUE THREAD

**Issue by olcova** [cosanlab/nltools#419]
Why are the beta images cut from the front in Mango and cut from the back in nltools? 

![plot in nltools](https://github.com/cosanlab/nltools/assets/139748079/4b6c53c5-2c6a-43eb-aa58-6cdd964c95b1)

**Comment by ejolly** [comment]
Hey @olcova this is an interaction between the coverage you had during fMRI acquisition and the different MNI template spaces nltools uses vs Mango. You can checkout the templates we're using here: https://github.com/cosanlab/nltools/tree/master/nltools/resources
