### ISSUE TITLE
isc() got an unexpected keyword argument 'n_bootstraps'

### ISSUE THREAD

**Issue by annikabrueckner** [cosanlab/nltools#427]
Dear all, 
can you help me fix the error message? 
I imported all necessary packages from the nltools-module. 
Code imported from Tutorial of Chang et al., about the Intersubject Representational Similarty Analysis (https://naturalistic-data.org/content/Intersubject_RSA.html#calculate-behavioral-similarity)

isc = {node:similarity_matrices[node].isc(metric='mean', n_bootstraps=1, n_jobs=1)['isc'] for node in range(n_nodes)}

**Comment by ljchang** [comment]
Hi @annikabrueckner, Sorry for the delay in responding.

This is an error resulting from a small change we made to the keyword arguments in the ISC function.  `n_bootstraps` is now `n_samples`. See if that fixes your issue. I've also updated the tutorial on naturalistic-data.

Thanks for letting us know you ran into this error. This is the main way we can keep the tutorials up to date.
